prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "docker_context",
    "package",
    "dotnet",
    "elixir",
    "elm",
    "golang",
    "haskell",
    "java",
    "julia",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "conda",
    "memory_usage",
    #"aws",
    "env_var",
    "crystal",
    "cmd_duration",
    "custom",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]

add_newline = false

[character]      # The name of the module we are configuring is "character"
symbol = "$"     # The "symbol" segment is being set to "➜"

[kubernetes]
disabled = false

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"
[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"
[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[git_branch]
# truncation_length = 26

[aws.region_aliases]
us-east-1 = "N. Virginia"
us-east-2 = "Ohio"
us-west-1 = "N. California"
us-west-2 = "Oregon"
ap-east-1 = "Hong Kong"
ap-south-1 = "Mumbai"
ap-northeast-1 = "Tokyo"
ap-northeast-2 = "Seoul"
ap-northeast-3 = "Osaka"
ap-southeast-1 = "Singapore"
ap-southeast-2 = "Sydney"
ca-central-1 = "Canada (Central)"
cn-north-1 = "Beijing"
cn-northwest-1 = "Ningxia"
eu-central-1 = "Frankfurt"
eu-west-1 = "Ireland"
eu-west-2 = "London"
eu-west-3 = "Paris"
eu-north-1 = "Stockholm"
me-south-1 = "Bahrain"
sa-east-1 = "Sao Paulo"
us-gov-east-1 = "US-East GOV"
us-gov-west-1 = "US-West GOV"
